### ISSUE TITLE
[REQ] ieee.opensutd.org

### ISSUE THREAD

**Issue by flamanta** [OpenSUTD/subdomains#1]
**Project Info**

Source URL if any: https://sutd-ieee.github.io/

Link to repository URL: https://github.com/SUTD-IEEE/SUTD-IEEE.github.io

**DNS records needed**
CNAME

name: ieee.opensutd.org
value: sutd-ieee.github.io

**Brief description of the project**
A short description of what the page is about:

It is the club website as well as a landing page for potential IEEE student branch members to find out more about the weekly activities being held.

In addition to the club website, IEEE student members of our student branch have the added benefit of gaining access to an internal inventory loaning system where they can loan out equipment from the student branch.

**Project owners**
Tag project owners (@username) : @flamanta, @xmliszt

**Comment by tlkh** [comment]
https://ieee.opensutd.org should be working now.

Please remember to set custom domain in your GitHub repository and wait a few seconds before trying.

**Comment by flamanta** [comment]
The custom domain works now. Thank you!
