### ISSUE TITLE
[REQ] soar.opensutd.org

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/subdomains#10]
**Project Info**

Source URL if any: https://sutdsoar.netlify.com/

Link to repository URL: https://github.com/sutd-robotics/sutdsoar

**DNS records needed**
CNAME

name: soar.opensutd.org
value: sutdsoar.netlify.com

**Brief description of the project**
A short description of what the page is about:

SOAR Club Website.

**Project owners**
Tag project owners (@username) : @jamestiotio @ulaladungdung

**Comment by tlkh** [comment]
Done, created [soar.opensutd.org](https://soar.opensutd.org), can you please test it out?

**Comment by jamestiotio** [comment]
Yup, it's up. Thank you!
