### ISSUE TITLE
[REQ] heidegger.opensutd.org, qct.opensutd.org

### ISSUE THREAD

**Issue by flamanta** [OpenSUTD/subdomains#12]
**Project Info**
Digitising Heidegger's The Question Concerning Technology

1. Source URL if any: https://sutd-heidegger.github.io/
Link to repository URL: https://github.com/SUTD-Heidegger/SUTD-Heidegger.github.io

2. Source URL if any: https://flamanta.gitbook.io/qct/

**DNS records needed**

1. CNAME
name: heidegger.opensutd.org
value: SUTD-Heidegger.github.io

2. CNAME
name: qct.opensutd.org
value: hosting.gitbook.com

**Brief description of the project**
This is a Digital Humanities project as part of the _02.132HT The Question of Technology_ course at the Singapore University of Technology and Design.

Heidegger’s work is a monolithic endeavour with over 100 volumes. Though much has been
translated to English, the works have not yet been digitised online, constraining research to
individual experts of the field. The aim of this project is to digitalise Heidegger's work to simplify the learning process of understanding Heidegger’s thought.

I was originally thinking of parking the GitHub Pages repository and the GitBook under the same subdomain, but seems like it is not possible, hence the request for 2 subdomains instead.

**Project owners**
Tag project owners (@username): @flamanta

**Comment by tlkh** [comment]
Done, can you check?

**Comment by flamanta** [comment]
Great, the links work! Thank you for your help.
