### ISSUE TITLE
[REQ] sutdcf.opensutd.org

### ISSUE THREAD

**Issue by ERJoseJohnson** [OpenSUTD/subdomains#14]
**Project Info**
SUTDCF Official Website

Source URL if any: https://erjosejohnson.github.io/

Link to repository URL: https://github.com/ERJoseJohnson/ERJoseJohnson.github.io

**DNS records needed**
CNAME

name: sutdcf.opensutd.org
value: erjosejohnson.github.io

**Brief description of the project**
A short description of what the page is about:
A website that contains details about SUTDCF for any student interested.

**Project owners**
Tag project owners (@username) : @ERJoseJohnson

**Comment by tlkh** [comment]
DNS has been configured for `sutdcf.opensutd.org`

Please go to **your** repo (https://github.com/ERJoseJohnson/ERJoseJohnson.github.io) and set the custom domain to `sutdcf.opensutd.org`. You may need to republish the page for it to take effect (e.g. edit the README file or something to get the site to rebuild. 

@ERJoseJohnson

**Comment by ERJoseJohnson** [comment]
Works great!

Thanks a bunch for the speedy implementation! :D

**Comment by jamestiotio** [comment]
Closing this issue since the site is already up and live and confirmation has been received.
