### ISSUE TITLE
[REQ] hkn.opensutd.org

### ISSUE THREAD

**Issue by flamanta** [OpenSUTD/subdomains#16]
**Project Info**

Source URL if any: https://sutd-hkn.github.io/

Link to repository URL: https://github.com/SUTD-HKN/SUTD-HKN.github.io

**DNS records needed**
CNAME

name: hkn.opensutd.org
value: sutd-hkn.github.io

**Brief description of the project**
A short description of what the page is about:

It is the website and blog of Eta Kappa Nu, Mu Epsilon chapter at SUTD.

Eta Kappa Nu or IEEE-HKN is the international honor society for the Institute of Electrical and Electronics Engineers (IEEE).

**Project owners**
Tag project owners (@username) : @flamanta

**Comment by tlkh** [comment]
Done pls set custom URL and test

**Comment by flamanta** [comment]
Ok it works thanks so much!
