### ISSUE TITLE
[REQ] 50043-group10.opensutd.org

### ISSUE THREAD

**Issue by caspycat** [OpenSUTD/subdomains#17]
**Project Info**

Source URL if any: not yet

Link to repository URL: not yet

**DNS records needed**
NS

name: 50043-group10.opensutd.org
values:
ns-873.awsdns-45.net.
ns-79.awsdns-09.com.
ns-1795.awsdns-32.co.uk.
ns-1396.awsdns-46.org.

**Brief description of the project**
A short description of what the page is about: Our group project for [50.043 Databases and Big Data](https://istd50043.github.io/project).

**Project owners**
Tag project owners (@username) : @chesnutcase

**Comment by caspycat** [comment]
done

**Comment by tlkh** [comment]
kek
