### ISSUE TITLE
[REQ] 3dc.opensutd.org

### ISSUE THREAD

**Issue by MarkHershey** [OpenSUTD/subdomains#19]
**Project Info**

Source URL if any: [https://3dcdsc.github.io/](https://3dcdsc.github.io/) 

Link to repository URL: [https://github.com/3DCdsc/3dcdsc.github.io](https://github.com/3DCdsc/3dcdsc.github.io)

**DNS records needed**
CNAME

name: `3dc.opensutd.org`
value: `3dcdsc.github.io`

**Brief description of the project**
Digital Design and Development Club (3DC) Website

**Project owners**
Tag project owners: @3DCdsc @MarkHershey

**Comment by tlkh** [comment]
DNS has been configured.

Please go to your repo and set the custom domain to 3dc.opensutd.org. If you are using GitHub pages, you may need to republish the page for it to take effect (e.g. edit the README file or do something to get the site to rebuild)

**Comment by MarkHershey** [comment]
Confirmed: the site is live at [https://3dc.opensutd.org/](https://3dc.opensutd.org/), thanks @tlkh

**Comment by jamestiotio** [comment]
Closing this issue since the site is already up and live and confirmation has been received.
