### ISSUE TITLE
[REQ] course-planner.opensutd.org

### ISSUE THREAD

**Issue by coddyzz** [OpenSUTD/subdomains#2]
**Project Info**

Source URL if any: https://opensutd.org/study-planner/

Link to repository URL:  https://github.com/OpenSUTD/study-planner

```
# example
Source URL if any: https://example.github.io/
Link to repository URL: https://github.com/example/test
```

**DNS records needed**
CNAME

name: course-planner.opensutd.org
value: opensutd.org/study-planner/

```
# example
name: example.opensutd.org
value: example.github.io
```

**Brief description of the project**
A short description of what the page is about:

course planner for Term 4 to 8

**Project owners**
Tag project owners (@username) : @coddyzz

**Comment by tlkh** [comment]
@coddyzz confirm it works as expected:

https://course-planner.opensutd.org/
