### ISSUE TITLE
[REQ] subdomain.opensutd.org

### ISSUE THREAD

**Issue by weiying98** [OpenSUTD/subdomains#3]
**Project Info**

Source URL if any:  https://weiying98.github.io/EPD/

Link to repository URL: https://github.com/weiying98/EPD

```
# example
Source URL if any: https://example.github.io/
Link to repository URL: https://github.com/example/test
```

**DNS records needed**
CNAME

name: EPD.opensutd.org
value: EPD.github.io

```
# example
name: example.opensutd.org
value: example.github.io
```

**Brief description of the project**
A short description of what the page is about:
EPD Student initiatives and Resources

**Project owners**
Tag project owners (@username) :
@weiying98

**Comment by tlkh** [comment]
done
