### ISSUE TITLE
[REQ] gunpla.opensutd.org

### ISSUE THREAD

**Issue by piroton** [OpenSUTD/subdomains#4]
**Project Info**

Source URL if any: https://piroton.github.io/sutd-gunpla-site/

Link to repository URL:  https://github.com/piroton/sutd-gunpla-site

```
# example
Source URL if any: https://example.github.io/
Link to repository URL: https://github.com/example/test
```

**DNS records needed**
CNAME

name: gunpla.opensutd.org
value: https://piroton.github.io/sutd-gunpla-site/

```
# example
name: example.opensutd.org
value: example.github.io
```

**Brief description of the project**
A short description of what the page is about:

Gunpla Club website.

**Project owners**
Tag project owners (@username) : @piroton 
The temporary site is up!

**Comment by piroton** [comment]
Updated with repository!

**Comment by tlkh** [comment]
should be working fine now
