### ISSUE TITLE
[REQ] greenprint.opensutd.org

### ISSUE THREAD

**Issue by Jaryllim98** [OpenSUTD/subdomains#5]
**Project Info**
Greenprint static page

Source URL if any: https://jaryllim98.github.io/Greenprint/
Link to repository URL: https://github.com/Jaryllim98/Greenprint/

**DNS records needed**
CNAME

name: greenprint.opensutd.org
value: greenprint.github.io

**Brief description of the project**
A short description of what the page is about: Test Page of Greenprint

**Project owners**
Tag project owners (@jaryllim98) :

**Comment by tlkh** [comment]
Hi @Jaryllim98 I have provisioned greenprint.opensutd.org.

Please go to **your** repository settings, scroll down to GitHub Pages, and enter `greenprint.opensutd.org` under "Custom Domain". The next time you edit and save the page, greenprint.opensutd.org will work.
