### ISSUE TITLE
[REQ] sutdvolleyball.opensutd.org

### ISSUE THREAD

**Issue by tanshinjie** [OpenSUTD/subdomains#6]
**Project Info**

Source URL if any: 

Link to repository URL: https://github.com/tanshinjie/Volleyball

```
# example
Source URL if any: https://example.github.io/
Link to repository URL: https://github.com/example/test
```

**DNS records needed**
CNAME

name: sutdvolleyball.opensutd.org
value: example.github.io

```
# example
name: example.opensutd.org
value: example.github.io
```

**Brief description of the project**
A short description of what the page is about:
Static landing page for sutd volleyball club

**Project owners**
Tag project owners (@username) : @tanshinjie

**Comment by tlkh** [comment]
@tanshinjie we have allocated sutdvolleyball.opensutd.org

Please go to your repository settings, scroll down to GitHub Pages, and enter sutdvolleyball.opensutd.org under "Custom Domain". The next time you edit and save the page, sutdvolleyball.opensutd.org will work.

**Comment by piroton** [comment]
I checked, it's done. Closing.
