### ISSUE TITLE
[REQ] sutdio.opensutd.org

### ISSUE THREAD

**Issue by sl194** [OpenSUTD/subdomains#7]
**Project Info**
Source URL if any: https://sl194.github.io/sutdio/
Link to repository URL: https://github.com/sl194/sutdio

**DNS records needed**
CNAME
Name: sutdio.opensutd.org
Value: https://sl194.github.io/sutdio/

**Brief description of the project**
A short description of what the page is about: SUTDio website

**Project owners**
Tag project owners (@username) : @sl194

The temporary site is up!

**Comment by tlkh** [comment]
sutdio.opensutd.org has been allocated.

Please go to **your repository settings**, scroll down to **GitHub Pages**, and enter `sutdio.opensutd.org` under "Custom Domain". The next time you edit and save the page, sutdio.opensutd.org will work. It should work after about one min at most.

**Comment by piroton** [comment]
I checked, they've done it. Closing issue.
